name: Publish NuGet Packages
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Package Version'     
        required: true
        default: ''

#    echo "Log level: ${{ github.event.inputs.logLevel }}"
jobs:
  publish:
    name: Publish NuGet 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Publish Net50
        id: publish_nuget_net50
        uses: rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: Basic.Reference.Assemblies.Net50/Basic.Reference.Assemblies.Net50.csproj
          VERSION_STATIC: ${{ github.event.inputs.version }}
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: Publish NetCoreApp31
        id: publish_nuget_netcoreapp31
        uses: rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: Basic.Reference.Assemblies.NetCoreApp31/Basic.Reference.Assemblies.NetCoreApp31.csproj
          VERSION_STATIC: ${{ github.event.inputs.version }}
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: Publish NetStandard20
        id: publish_nuget_netstandard20
        uses: rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: Basic.Reference.Assemblies.NetStandard20/Basic.Reference.Assemblies.NetStandard20.csproj
          VERSION_STATIC: ${{ github.event.inputs.version }}
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
