name: Publish NuGet Packages
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Package Version'     
        required: true
        default: ''

#    echo "Log level: ${{ github.event.inputs.logLevel }}"
jobs:
  publish:
    name: Publish NuGet 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build 
        run: dotnet build -c Release 
      
      - name: Pack Net50
        run: dotnet pack --no-build -p:PackageVersion="${{ github.events.inputs.version }}" -c Release Basic.Reference.Assemblies.Net50/Basic.Reference.Assemblies.Net50.csproj -o .

      - name: Pack NetCoreApp31
        run: dotnet pack --no-build -p:PackageVersion="${{ github.events.inputs.version }}" -c Release Basic.Reference.Assemblies.NetCoreApp31/Basic.Reference.Assemblies.NetCoreApp31.csproj -o .

      - name: Pack NetStandard20
        run: dotnet pack --no-build -p:PackageVersion="${{ github.events.inputs.version }}" -c Release Basic.Reference.Assemblies.NetStandard20/Basic.Reference.Assemblies.NetStandard20.csproj -o .

      - name: Publish NuPkg Files
        run: dotnet nuget push -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --no-symbols *.nupkg